### ISSUE TITLE
Getting error when use multiple charts

### ISSUE THREAD

**Issue by HaiAlison** [objectum/xlsx-chart#21]
I have an issue when create multiple charts, can anyone help me.. 
this is my opts below
`
const opts = {

          charts: [
            {
              chart: 'line',
              titles: ['inside', 'outside'],
              fields: [
                '29-06-2022, 14:15:01',
                '29-06-2022, 14:30:10',
              ],
              data: {
                outside: {
                  '29-06-2022, 14:15:01': 44,
                  '29-06-2022, 14:30:10': 42,
                },
                inside: {
                  '29-06-2022, 14:15:01': 37,
                  '29-06-2022, 14:30:10': 35,
                },
              },
              chartTitle: 'Temperature',
            },
            {
              chart: 'column',
              titles: ['inside', 'outside'],
              fields: [
                '29-06-2022, 14:15:01',
                '29-06-2022, 14:30:10',
              ],
              data: {
                outside: {
                  '29-06-2022, 14:15:01': 66,
                  '29-06-2022, 14:30:10': 67,
                },
                inside: {
                  '29-06-2022, 14:15:01': 91,
                  '29-06-2022, 14:30:10': 92,
                },
              },
              chartTitle: 'humidity',
            },
          ],
        };`

and i get error like this below:

`
TypeError: Cannot set properties of undefined (setting 'c:ser')
    at /Users/haialison/IdeaProjects/digifarm-be/node_modules/xlsx-chart/chart/base.js:509:83
    at Function.each (/Users/haialison/IdeaProjects/digifarm-be/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at /Users/haialison/IdeaProjects/digifarm-be/node_modules/xlsx-chart/chart/base.js:494:6
    at /Users/haialison/IdeaProjects/digifarm-be/node_modules/xlsx-chart/chart/base.js:20:4
    at Parser.<anonymous> (/Users/haialison/IdeaProjects/digifarm-be/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:390:28)
    at SAXParser.onclosetag (/Users/haialison/IdeaProjects/digifarm-be/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/Users/haialison/IdeaProjects/digifarm-be/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/haialison/IdeaProjects/digifarm-be/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/haialison/IdeaProjects/digifarm-be/node_modules/sax/lib/sax.js:889:7)
`

**Comment by HaiAlison** [comment]
[fix adding Line chart for multi-chart config](https://github.com/objectum/xlsx-chart/pull/19/commits/00bf5cadd06a8e25051dbefeeda73cd1cd873bea)
